dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
  - "6"
  - "4"
env:
  - GO_VERSION=1.9.5
  - GO_VERSION=1.10.1
cache:
  directories:
    - node_modules
install:
  - 'eval "$(gimme ${GO_VERSION})"'
  - 'go version'
script:
  - "npm install"
  - "npm test"
jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: skip
      after_success:
        - npm run semantic-release
branches:
  only:
    - master
