dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
  - "6"
  - "4"
  - "0.12"
cache:
  directories:
    - node_modules
script: npm test
branches:
  only:
    - master
